/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LibrosBuscarPorTituloView.java
 *
 * Created on 04-may-2011, 19:32:43
 */

package biblioadmin2;

import com.db4o.ObjectSet;
import com.sun.xml.internal.bind.v2.schemagen.xmlschema.LocalAttribute;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import locators.ModelLocator;
import managers.LibroManager;
import models.Libro;
import org.jdesktop.application.Action;

/**
 *
 * @author agustinmoyano
 */
public class LibrosBuscarPorTituloView extends javax.swing.JFrame {

    /** Creates new form LibrosBuscarPorTituloView */
    public LibrosBuscarPorTituloView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label3 = new java.awt.Label();
        txtTituloLibro = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listLibros = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        label3.setName("label3"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(biblioadmin2.BiblioAdmin2App.class).getContext().getResourceMap(LibrosBuscarPorTituloView.class);
        label3.setText(resourceMap.getString("label3.text")); // NOI18N

        txtTituloLibro.setName("txtTituloLibro"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(biblioadmin2.BiblioAdmin2App.class).getContext().getActionMap(LibrosBuscarPorTituloView.class, this);
        jButton5.setAction(actionMap.get("buscarLibros")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        listLibros.setName("listLibros"); // NOI18N
        jScrollPane2.setViewportView(listLibros);

        jButton3.setAction(actionMap.get("cancelar")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        jButton2.setAction(actionMap.get("eliminarLibro")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton1.setAction(actionMap.get("showLibroModificar")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jButton1)
                        .add(18, 18, 18)
                        .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .add(18, 18, 18)
                        .add(jButton3))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 385, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(layout.createSequentialGroup()
                            .add(label3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(1, 1, 1)
                            .add(txtTituloLibro))
                        .add(layout.createSequentialGroup()
                            .add(292, 292, 292)
                            .add(jButton5))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(label3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtTituloLibro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    @Action
    public void cancelar() {
        this.dispose();
    }

    @Action
    public void showLibroModificar() {
     
      ModelLocator.getInstance().libroSeleccionado = (Libro) this.listLibros.getSelectedValue();
      if (libroModificarView == null) {
            JFrame mainFrame = BiblioAdmin2App.getApplication().getMainFrame();
            libroModificarView = new LibrosModificarView();
            libroModificarView.setLocationRelativeTo(mainFrame);
        }
        libroModificarView.show();
     

   
    }

    @Action
    public void buscarLibros() {
        ObjectSet<Libro> libros;
   

        libros  = LibroManager.getInstance().buscar(null, this.txtTituloLibro.getText(), null);

//PREGUNTAR TULIO PARA QUE SE VEA EL CAMPO TITULO Y QUE ACEPTE OBJECTSET LA LISTA
      this.listLibros.setListData(libros.toArray());
     

    }

    @Action
    public void eliminarLibro() {
        Boolean libroEliminado = LibroManager.getInstance().darDeBaja((Libro) this.listLibros.getSelectedValue());
        
    }
    private JFrame libroModificarView;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label3;
    private javax.swing.JList listLibros;
    private javax.swing.JTextField txtTituloLibro;
    // End of variables declaration//GEN-END:variables

}
