/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientesView.java
 *
 * Created on 06-may-2011, 13:18:41
 */

package biblioadmin2;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import managers.SocioManager;
import models.Localidad;
import models.Provincia;
import models.Rol;
import models.Socio;
import models.TipoSocio;
import org.jdesktop.application.Action;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;

/**
 *
 * @author agustinmoyano
 */
public class SociosView extends javax.swing.JFrame {

    /** Creates new form ClientesView */
    public SociosView() {
        initComponents();
        this.pnlDatosBuscar.hide();
        this.pnlDatosNuevo.hide();
        this.btnEliminarSocio.disable();
        this.btnModificarSocio.disable();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipoSocio = new javax.swing.ButtonGroup();
        grpTipoSocioMod = new javax.swing.ButtonGroup();
        tabSociosPanel = new javax.swing.JTabbedPane();
        pnlBuscar = new javax.swing.JPanel();
        txtDNINuevo = new javax.swing.JTextField();
        lblDNI1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        pnlDatosNuevo = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtApellidoSocio = new javax.swing.JTextField();
        btnAgregarSocio = new javax.swing.JButton();
        cbxLocalidad = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEmailSocio = new javax.swing.JTextField();
        txtDireccionSocio = new javax.swing.JTextField();
        rbProfesor = new javax.swing.JRadioButton();
        rbAlumno = new javax.swing.JRadioButton();
        cbxProvincia = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMaterias = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        txtTelefonoSocio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreSocio = new javax.swing.JTextField();
        pnlNuevo = new javax.swing.JPanel();
        lblDNI = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblDNI2 = new javax.swing.JLabel();
        txtDNIBuscar = new javax.swing.JTextField();
        btnBuscarSocio = new javax.swing.JButton();
        pnlDatosBuscar = new javax.swing.JPanel();
        cbxLocalidadMod = new javax.swing.JComboBox();
        txtApellidoMod = new javax.swing.JTextField();
        txtDireccionMod = new javax.swing.JTextField();
        txtEmailMod = new javax.swing.JTextField();
        txtTelMod = new javax.swing.JTextField();
        txtNombreMod = new javax.swing.JTextField();
        cbxProvinciaMod = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnEliminarSocio = new javax.swing.JButton();
        btnModificarSocio = new javax.swing.JButton();
        lblTipoSocio = new javax.swing.JLabel();
        txtMateriasMod = new javax.swing.JTextField();
        rbAlumnoMod = new javax.swing.JRadioButton();
        rbProfesorMod = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        tabSociosPanel.setName("tabSociosPanel"); // NOI18N

        pnlBuscar.setName("pnlBuscar"); // NOI18N

        txtDNINuevo.setName("txtDNINuevo"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(biblioadmin2.BiblioAdmin2App.class).getContext().getResourceMap(SociosView.class);
        lblDNI1.setText(resourceMap.getString("lblDNI1.text")); // NOI18N
        lblDNI1.setName("lblDNI1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(biblioadmin2.BiblioAdmin2App.class).getContext().getActionMap(SociosView.class, this);
        jButton6.setAction(actionMap.get("buscarNuevo")); // NOI18N
        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N

        pnlDatosNuevo.setName("pnlDatosNuevo"); // NOI18N

        jButton10.setAction(actionMap.get("limpiarCampos")); // NOI18N
        jButton10.setText(resourceMap.getString("jButton10.text")); // NOI18N
        jButton10.setName("jButton10"); // NOI18N

        jButton9.setAction(actionMap.get("cancelar")); // NOI18N
        jButton9.setText(resourceMap.getString("jButton9.text")); // NOI18N
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        txtApellidoSocio.setName("txtApellidoSocio"); // NOI18N

        btnAgregarSocio.setAction(actionMap.get("agregarSocio")); // NOI18N
        btnAgregarSocio.setText(resourceMap.getString("btnAgregarSocio.text")); // NOI18N
        btnAgregarSocio.setName("btnAgregarSocio"); // NOI18N

        cbxLocalidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Caleta Olivia", "Comodoro Rivadavia", "Pico Truncado", "Puerto Deseado", "Rada Tilly", " " }));
        cbxLocalidad.setName("cbxLocalidad"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        txtEmailSocio.setName("txtEmailSocio"); // NOI18N

        txtDireccionSocio.setName("txtDireccionSocio"); // NOI18N

        grpTipoSocio.add(rbProfesor);
        rbProfesor.setText(resourceMap.getString("rbProfesor.text")); // NOI18N
        rbProfesor.setName("rbProfesor"); // NOI18N

        grpTipoSocio.add(rbAlumno);
        rbAlumno.setText(resourceMap.getString("rbAlumno.text")); // NOI18N
        rbAlumno.setName("rbAlumno"); // NOI18N

        cbxProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chubut", "Santa Cruz", " " }));
        cbxProvincia.setName("cbxProvincia"); // NOI18N

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        txtMaterias.setColumns(20);
        txtMaterias.setRows(5);
        txtMaterias.setName("txtMaterias"); // NOI18N
        jScrollPane2.setViewportView(txtMaterias);

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        txtTelefonoSocio.setName("txtTelefonoSocio"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        txtNombreSocio.setName("txtNombreSocio"); // NOI18N

        org.jdesktop.layout.GroupLayout pnlDatosNuevoLayout = new org.jdesktop.layout.GroupLayout(pnlDatosNuevo);
        pnlDatosNuevo.setLayout(pnlDatosNuevoLayout);
        pnlDatosNuevoLayout.setHorizontalGroup(
            pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 507, Short.MAX_VALUE)
            .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(pnlDatosNuevoLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(pnlDatosNuevoLayout.createSequentialGroup()
                            .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel10)
                                .add(jLabel11)
                                .add(jLabel12)
                                .add(jLabel13)
                                .add(jLabel14)
                                .add(jLabel15)
                                .add(jLabel16)
                                .add(jLabel18)
                                .add(jLabel19))
                            .add(122, 122, 122)
                            .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(pnlDatosNuevoLayout.createSequentialGroup()
                                    .add(rbAlumno)
                                    .add(18, 18, 18)
                                    .add(rbProfesor))
                                .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtApellidoSocio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtNombreSocio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtDireccionSocio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .add(cbxLocalidad, 0, 0, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, cbxProvincia, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtTelefonoSocio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtEmailSocio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(pnlDatosNuevoLayout.createSequentialGroup()
                            .add(63, 63, 63)
                            .add(btnAgregarSocio)
                            .add(18, 18, 18)
                            .add(jButton10)
                            .add(9, 9, 9)
                            .add(jButton9)))
                    .addContainerGap(55, Short.MAX_VALUE)))
        );
        pnlDatosNuevoLayout.setVerticalGroup(
            pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 471, Short.MAX_VALUE)
            .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(pnlDatosNuevoLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(txtNombreSocio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel10))
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(txtApellidoSocio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel11))
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(txtDireccionSocio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel12))
                    .add(12, 12, 12)
                    .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(cbxLocalidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel13))
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(cbxProvincia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel14))
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(txtTelefonoSocio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel15))
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(txtEmailSocio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel16))
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                    .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(rbAlumno)
                        .add(rbProfesor)
                        .add(jLabel18))
                    .add(27, 27, 27)
                    .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel19))
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(pnlDatosNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButton9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButton10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(btnAgregarSocio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        org.jdesktop.layout.GroupLayout pnlBuscarLayout = new org.jdesktop.layout.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlBuscarLayout.createSequentialGroup()
                        .add(lblDNI1)
                        .add(88, 88, 88)
                        .add(txtDNINuevo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(34, 34, 34)
                        .add(jButton6))
                    .add(pnlDatosNuevo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(lblDNI1)
                        .add(txtDNINuevo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jButton6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlDatosNuevo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabSociosPanel.addTab(resourceMap.getString("pnlBuscar.TabConstraints.tabTitle"), pnlBuscar); // NOI18N

        pnlNuevo.setName("pnlNuevo"); // NOI18N

        lblDNI.setName("lblDNI"); // NOI18N

        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setName("jLabel9"); // NOI18N

        lblDNI2.setText(resourceMap.getString("lblDNI2.text")); // NOI18N
        lblDNI2.setName("lblDNI2"); // NOI18N

        txtDNIBuscar.setName("txtDNIBuscar"); // NOI18N

        btnBuscarSocio.setAction(actionMap.get("buscarModificar")); // NOI18N
        btnBuscarSocio.setText(resourceMap.getString("btnBuscarSocio.text")); // NOI18N
        btnBuscarSocio.setName("btnBuscarSocio"); // NOI18N

        pnlDatosBuscar.setName("pnlDatosBuscar"); // NOI18N

        cbxLocalidadMod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Caleta Olivia", "Comodoro Rivadavia", "Pico Truncado", "Puerto Deseado", "Rada Tilly", " " }));
        cbxLocalidadMod.setName("cbxLocalidadMod"); // NOI18N

        txtApellidoMod.setName("txtApellidoMod"); // NOI18N

        txtDireccionMod.setName("txtDireccionMod"); // NOI18N

        txtEmailMod.setName("txtEmailMod"); // NOI18N

        txtTelMod.setName("txtTelMod"); // NOI18N

        txtNombreMod.setName("txtNombreMod"); // NOI18N

        cbxProvinciaMod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chubut", "Santa Cruz", " " }));
        cbxProvinciaMod.setName("cbxProvinciaMod"); // NOI18N

        jButton4.setAction(actionMap.get("cancelar")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N

        btnEliminarSocio.setAction(actionMap.get("eliminarSocio")); // NOI18N
        btnEliminarSocio.setText(resourceMap.getString("btnEliminarSocio.text")); // NOI18N
        btnEliminarSocio.setName("btnEliminarSocio"); // NOI18N

        btnModificarSocio.setAction(actionMap.get("modificarSocio")); // NOI18N
        btnModificarSocio.setText(resourceMap.getString("btnModificarSocio.text")); // NOI18N
        btnModificarSocio.setName("btnModificarSocio"); // NOI18N

        lblTipoSocio.setText(resourceMap.getString("lblTipoSocio.text")); // NOI18N
        lblTipoSocio.setName("lblTipoSocio"); // NOI18N

        txtMateriasMod.setText(resourceMap.getString("txtMateriasMod.text")); // NOI18N
        txtMateriasMod.setName("txtMateriasMod"); // NOI18N

        grpTipoSocioMod.add(rbAlumnoMod);
        rbAlumnoMod.setText(resourceMap.getString("rbAlumnoMod.text")); // NOI18N
        rbAlumnoMod.setName("rbAlumnoMod"); // NOI18N

        grpTipoSocioMod.add(rbProfesorMod);
        rbProfesorMod.setText(resourceMap.getString("rbProfesorMod.text")); // NOI18N
        rbProfesorMod.setName("rbProfesorMod"); // NOI18N

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N

        org.jdesktop.layout.GroupLayout pnlDatosBuscarLayout = new org.jdesktop.layout.GroupLayout(pnlDatosBuscar);
        pnlDatosBuscar.setLayout(pnlDatosBuscarLayout);
        pnlDatosBuscarLayout.setHorizontalGroup(
            pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlDatosBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlDatosBuscarLayout.createSequentialGroup()
                        .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel17)
                            .add(jLabel20)
                            .add(jLabel21)
                            .add(jLabel22)
                            .add(jLabel23)
                            .add(jLabel24)
                            .add(jLabel25)
                            .add(jLabel26))
                        .add(50, 50, 50)
                        .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlDatosBuscarLayout.createSequentialGroup()
                                .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(txtApellidoMod, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .add(txtNombreMod, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .add(txtDireccionMod, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cbxLocalidadMod, 0, 0, Short.MAX_VALUE)
                                    .add(cbxProvinciaMod, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(txtTelMod, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .add(txtEmailMod, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 86, Short.MAX_VALUE)
                                .add(lblTipoSocio)
                                .add(82, 82, 82))
                            .add(pnlDatosBuscarLayout.createSequentialGroup()
                                .add(rbAlumnoMod)
                                .add(18, 18, 18)
                                .add(rbProfesorMod)
                                .addContainerGap())))
                    .add(pnlDatosBuscarLayout.createSequentialGroup()
                        .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlDatosBuscarLayout.createSequentialGroup()
                                .add(jLabel27)
                                .add(50, 50, 50)
                                .add(txtMateriasMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(pnlDatosBuscarLayout.createSequentialGroup()
                                .add(jButton4)
                                .add(18, 18, 18)
                                .add(btnModificarSocio)
                                .add(36, 36, 36)
                                .add(btnEliminarSocio)))
                        .add(51, 51, 51))))
        );
        pnlDatosBuscarLayout.setVerticalGroup(
            pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlDatosBuscarLayout.createSequentialGroup()
                .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlDatosBuscarLayout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtNombreMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel17))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtApellidoMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel20))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtDireccionMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel21))
                        .add(12, 12, 12)
                        .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cbxLocalidadMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel22))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cbxProvinciaMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel23))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtTelMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel24))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtEmailMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel25)))
                    .add(pnlDatosBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(lblTipoSocio)))
                .add(18, 18, 18)
                .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(rbAlumnoMod)
                        .add(rbProfesorMod))
                    .add(jLabel26))
                .add(18, 18, 18)
                .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel27)
                    .add(txtMateriasMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnlDatosBuscarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnModificarSocio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnEliminarSocio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout pnlNuevoLayout = new org.jdesktop.layout.GroupLayout(pnlNuevo);
        pnlNuevo.setLayout(pnlNuevoLayout);
        pnlNuevoLayout.setHorizontalGroup(
            pnlNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblDNI)
                    .add(jLabel3)
                    .add(pnlNuevoLayout.createSequentialGroup()
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblDNI2)
                        .add(75, 75, 75)
                        .add(txtDNIBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(btnBuscarSocio))
                    .add(jLabel2)
                    .add(jLabel1)
                    .add(pnlNuevoLayout.createSequentialGroup()
                        .add(pnlNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel7)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(jLabel8)
                            .add(jLabel9))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlDatosBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pnlNuevoLayout.setVerticalGroup(
            pnlNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlNuevoLayout.createSequentialGroup()
                .add(pnlNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(pnlNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(btnBuscarSocio)
                        .add(lblDNI2)
                        .add(txtDNIBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(pnlNuevoLayout.createSequentialGroup()
                        .add(lblDNI)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(pnlNuevoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlNuevoLayout.createSequentialGroup()
                        .add(13, 13, 13)
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel7)
                        .add(18, 18, 18)
                        .add(jLabel8)
                        .add(44, 44, 44)
                        .add(jLabel9))
                    .add(pnlNuevoLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlDatosBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabSociosPanel.addTab(resourceMap.getString("pnlNuevo.TabConstraints.tabTitle"), pnlNuevo); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(tabSociosPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 581, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .add(tabSociosPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 565, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }

    @Action
    public void cancelar() {
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    @Action
    public void agregarSocio(){
        Socio socioNuevo = new Socio();
        Localidad localidadNueva = new Localidad();
        Provincia provinciaNueva = new Provincia();
        Rol rolNuevo = new Rol();
        TipoSocio tipoSocioNuevo = new TipoSocio();


        rolNuevo.nombre = this.grpTipoSocio.getSelection().toString();
        tipoSocioNuevo.rol = rolNuevo;
        tipoSocioNuevo.materias = this.txtMaterias.getText().toString();
        localidadNueva.nombre = this.cbxLocalidad.getSelectedItem().toString();
        provinciaNueva.nombre = this.cbxProvincia.getSelectedItem().toString();
        localidadNueva.provincia = provinciaNueva ;

        socioNuevo.dni = this.txtDNINuevo.getText().toString();
        socioNuevo.nombre = this.txtNombreSocio.getText().toString();
	socioNuevo.apellido = this.txtApellidoSocio.getText().toString();
	socioNuevo.telefono = this.txtTelefonoSocio.getText().toString();
        socioNuevo.email =  this.txtEmailSocio.getText().toString();
	socioNuevo.direccion = this.txtDireccionSocio.getText().toString();
	socioNuevo.localidad = localidadNueva;
	socioNuevo.dadoDeBaja = false;
	socioNuevo.tipoSocio = tipoSocioNuevo;
	socioNuevo.cantidadReservado = 0;

        SocioManager.getInstance().saveOrUpdate(socioNuevo);
    }

    @Action
    public void buscarNuevo() {
            try {
           this.existeSocio = SocioManager.getInstance().existe(this.txtDNINuevo.getText());
           if (this.existeSocio){
              
               JOptionPane.showMessageDialog(null, "YA EXISTE EL SOCIO CON ESE DNI", "ERROR", JOptionPane.ERROR_MESSAGE);

           }
        else{
             this.pnlDatosNuevo.show();
         }
        } catch (Exception ex) {
            Logger.getLogger(SociosView.class.getName()).log(Level.SEVERE, null, ex);
        }


    }

    @Action
    public void buscarModificar() {
            try {
           this.existeSocio = SocioManager.getInstance().existe(this.txtDNIBuscar.getText());
           if (this.existeSocio){
             this.pnlDatosBuscar.show();
             this.btnEliminarSocio.enable();
             this.btnModificarSocio.enable();
             
             Socio socioModificable = new Socio();
             socioModificable =  SocioManager.getInstance().buscar(this.txtDNIBuscar.getText());
             Localidad localidadMod = new Localidad();
             Provincia provinciaMod = new Provincia();
             Rol rolMod = new Rol();
             TipoSocio tipoSocioMod = new TipoSocio();

             provinciaMod = socioModificable.localidad.provincia;
             localidadMod = socioModificable.localidad;
             rolMod = socioModificable.tipoSocio.rol;
             tipoSocioMod = socioModificable.tipoSocio;
             
            

             this.txtNombreMod.setText(socioModificable.nombre);
             this.txtApellidoMod.setText(socioModificable.apellido);
             this.txtDireccionMod.setText(socioModificable.direccion);
             this.txtTelMod.setText(socioModificable.telefono);
             this.txtEmailMod.setText(socioModificable.email);
             this.cbxLocalidadMod.setSelectedItem(socioModificable.localidad.nombre);
             this.cbxProvinciaMod.setSelectedItem(socioModificable.localidad.provincia.nombre);
             this.txtMateriasMod.setText(socioModificable.tipoSocio.materias);
            

             if(socioModificable.tipoSocio.rol.nombre.equals("Alumno"))
             {
                this.rbAlumnoMod.setSelected(true);
                
             }
                 else{
                    this.rbProfesorMod.setSelected(true);
                   
            }
           }
        else{
           
            JOptionPane.showMessageDialog(null,"NO EXISTE EL SOCIO CON ESE DNI", "ERROR", JOptionPane.ERROR_MESSAGE);



         }
        } catch (Exception ex) {
            Logger.getLogger(SociosView.class.getName()).log(Level.SEVERE, null, ex);
        }


    }

    @Action
    public void eliminarSocio() {
        Boolean eliminado;
        Socio socioModificable = new Socio();
        socioModificable =  SocioManager.getInstance().buscar(this.txtDNIBuscar.getText());
        eliminado = SocioManager.getInstance().darDeBaja(socioModificable);
        if(eliminado){
            JOptionPane.showMessageDialog(null,"EL SOCIO FUE ELIMINADO", "SOCIO ELIMINADO", JOptionPane.INFORMATION_MESSAGE);
             this.txtNombreMod.setText(null);
             this.txtApellidoMod.setText(null);
             this.txtDireccionMod.setText(null);
             this.txtTelMod.setText(null);
             this.txtEmailMod.setText(null);
             this.txtMateriasMod.setText(null);
        }
         else{
             JOptionPane.showMessageDialog(null,"EL SOCIO NO FUE ELIMINADO", "SOCIO NO ELIMINADO", JOptionPane.WARNING_MESSAGE);
         }
        
    }

    @Action
    public void modificarSocio() {

        Socio socioModificable = new Socio();
        socioModificable =  SocioManager.getInstance().buscar(this.txtDNIBuscar.getText());
        Localidad localidadNueva = new Localidad();
        Provincia provinciaNueva = new Provincia();
        Rol rolNuevo = new Rol();
        TipoSocio tipoSocioNuevo = new TipoSocio();


        rolNuevo.nombre = this.grpTipoSocioMod.getSelection().toString();
        tipoSocioNuevo.rol = rolNuevo;
        tipoSocioNuevo.materias = this.txtMateriasMod.getText().toString();
        localidadNueva.nombre = this.cbxLocalidadMod.getSelectedItem().toString();
        provinciaNueva.nombre = this.cbxProvinciaMod.getSelectedItem().toString();
        localidadNueva.provincia = provinciaNueva ;

        socioModificable.dni = this.txtDNIBuscar.getText().toString();
        socioModificable.nombre = this.txtNombreMod.getText().toString();
	socioModificable.apellido = this.txtApellidoMod.getText().toString();
	socioModificable.telefono = this.txtTelMod.getText().toString();
        socioModificable.email =  this.txtEmailMod.getText().toString();
	socioModificable.direccion = this.txtDireccionMod.getText().toString();
	socioModificable.localidad = localidadNueva;
	socioModificable.tipoSocio = tipoSocioNuevo;
	

        SocioManager.getInstance().saveOrUpdate(socioModificable);
    }

    @Action
    public void limpiarCampos() {
             this.txtNombreSocio.setText(null);
             this.txtApellidoSocio.setText(null);
             this.txtDireccionSocio.setText(null);
             this.txtTelefonoSocio.setText(null);
             this.txtEmailSocio.setText(null);
             this.txtMaterias.setText(null);
    }

    private Boolean existeSocio;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarSocio;
    private javax.swing.JButton btnBuscarSocio;
    private javax.swing.JButton btnEliminarSocio;
    private javax.swing.JButton btnModificarSocio;
    private javax.swing.JComboBox cbxLocalidad;
    private javax.swing.JComboBox cbxLocalidadMod;
    private javax.swing.JComboBox cbxProvincia;
    private javax.swing.JComboBox cbxProvinciaMod;
    private javax.swing.ButtonGroup grpTipoSocio;
    private javax.swing.ButtonGroup grpTipoSocioMod;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDNI1;
    private javax.swing.JLabel lblDNI2;
    private javax.swing.JLabel lblTipoSocio;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlDatosBuscar;
    private javax.swing.JPanel pnlDatosNuevo;
    private javax.swing.JPanel pnlNuevo;
    private javax.swing.JRadioButton rbAlumno;
    private javax.swing.JRadioButton rbAlumnoMod;
    private javax.swing.JRadioButton rbProfesor;
    private javax.swing.JRadioButton rbProfesorMod;
    private javax.swing.JTabbedPane tabSociosPanel;
    private javax.swing.JTextField txtApellidoMod;
    private javax.swing.JTextField txtApellidoSocio;
    private javax.swing.JTextField txtDNIBuscar;
    private javax.swing.JTextField txtDNINuevo;
    private javax.swing.JTextField txtDireccionMod;
    private javax.swing.JTextField txtDireccionSocio;
    private javax.swing.JTextField txtEmailMod;
    private javax.swing.JTextField txtEmailSocio;
    private javax.swing.JTextArea txtMaterias;
    private javax.swing.JTextField txtMateriasMod;
    private javax.swing.JTextField txtNombreMod;
    private javax.swing.JTextField txtNombreSocio;
    private javax.swing.JTextField txtTelMod;
    private javax.swing.JTextField txtTelefonoSocio;
    // End of variables declaration//GEN-END:variables

}
